### ISSUE TITLE
Keybinding a specific "npm-script.run"

### ISSUE THREAD

**Issue by MLefebvreICO** [microsoft/vscode-npm-scripts#10]
Hi there,
Is it possible right now or in a future to add a keybind to run a specific `npm run`?
So let's say I have a `serve` npm script thats runs a webserver, 
I want to be able to make a shorcut let's say `CTRL+ALT+S` that would do something like this as command `npm-script.run serve`

**Comment by egamma** [comment]
Sorry this is currently not possible. 
You could imagine to have a `custom npm command` that is configured through settings, e.g,. the command string, then it would be possible to bind a key to this custom command.

**Comment by egamma** [comment]
This is now possible when using the platform provided tasks support, pls see https://code.visualstudio.com/docs/editor/tasks#_binding-keyboard-shortcuts-to-tasks
