### ISSUE TITLE
Breaking terminal reverse search

### ISSUE THREAD

**Issue by jamesiri** [microsoft/vscode-npm-scripts#106]
### Expected Action
In the integrated vscode terminal I should be able to hit `ctrl + r` and get a reverse search for my previous commands.

### What Actually Happens
This plug-in captures the terminal input and waits for additional inputs.

### Why This Is A Problem
There is no setting within your plug-in that details what it is waiting for or how to remap the command. So now I can't use your plug-in because retyping previously used long commands is not something I am going to do as it breaks my workflow.

**Comment by jamesiri** [comment]
Any updates or confirmation?

**Comment by fvelcker** [comment]
Same as https://github.com/microsoft/vscode-npm-scripts/issues/72
