### ISSUE TITLE
Is it possible to a stop watch task?

### ISSUE THREAD

**Issue by aflanagan** [Microsoft/vscode-npm-scripts#11]
I'm new to vscode, but I use a lot of npm scripts in my projects and this is a great plugin! 

I'm having trouble with one thing though -- I have a couple of watch type tasks (e.g. using `watchify`). I'm having trouble killing those tasks through vscode. Selecting `Tasks: Terminate Running Task` doesn't seem to kill any npm script I start using this plugin. Is there another way to end these tasks?

**Comment by egamma** [comment]
>Selecting  Tasks: Terminate Running Task  doesn't seem to kill any npm script I start using this plugin.

This action only apply to process that were started as tasks https://code.visualstudio.com/docs/editor/tasks.

In the insiders build we have added support for creating tasks from an npm package.json https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/latest.md#tasks

You can give it a try from our  [insiders build](https://code.visualstudio.com/blogs/2016/02/01/introducing_insiders_build) today: http://code.visualstudio.com/Download#insiders

**Comment by aflanagan** [comment]
Oh, fantastic! I'll give that a try.

**Comment by AppShipIt** [comment]
I switched over but is there any way for the plugin to start real tasks?

**Comment by egamma** [comment]
@AppShipIt you switched over from what? What is an example of a real task?

**Comment by AppShipIt** [comment]
For `npm start` I switched from using this extension to the npm tasks template in the Insiders build. I wondered whether there's any API to register a task in code for termination.

**Comment by AppShipIt** [comment]
Fixed by #13.
