### ISSUE TITLE
[bug] Task from another project is detected as already active

### ISSUE THREAD

**Issue by ceefour** [microsoft/vscode-npm-scripts#116]
In a multi-directory workspace, when trying to run a task in a project while another task with the same name (although different projects), `vscode-npm-scripts` will incorrectly prompt to Terminate/Restart:

```
The task 'npm: start:dev (...)' is already active.
```

## Steps to Reproduce

1. Open a workspace with 2 directories (better use NextJS in order to reproduce my issue).
2. Run npm script `start:dev` from project 1.
3. Run npm script `start:dev` from project 2.

## Expected

npm script `start:dev` from project 2 runs.

## Actual

```
The task 'npm: start:dev (project 1)' is already active.
```

## Workaround

Manually run the npm run-script task from Terminal, without using this extension. :(

**Comment by darylknowles** [comment]
I had this same issue.  The update for VS Code 1.44.0 fixes it, though there is no mention of the fix in the release notes.  I had an issue over on vs code ( https://github.com/microsoft/vscode/issues/92508) and closed it, but I am still curious about the fix.

**Comment by ceefour** [comment]
Closed as duplicate of https://github.com/microsoft/vscode/issues/92508

Thanks @darylknowles !
