### ISSUE TITLE
How do you stop a script?

### ISSUE THREAD

**Issue by zigomir** [Microsoft/vscode-npm-scripts#12]
I have `npm.runInTerminal` set to `false` so the output goes to `OUTPUT` pane inside Visual Studio Code editor. I'm running a watching + server script with npm script extension. How do I stop the server now?

**Comment by egamma** [comment]
This is a gap in the extension, sorry. 

To support this the extension needs to keep track of the spawned process and provide an action to terminate/kill the spawned process. 

I've turned this into a feature request.

**Comment by JonPSmith** [comment]
I have the same request. Is there a workround? I tried the command `Tasks: Terminate Running Task` but it didn't seem to find a task I could terminate.

Also, if it helps, a 'kill **all** npm tasks' would work for me.

**Comment by JonPSmith** [comment]
PS. Great extension!

**Comment by egamma** [comment]
@JonPSmith thanks. 

A workaround is to set `npm.runInTerminal` to `true` then you cancel the watch job by closing the terminal window.

The real fix is that the extension remembers that process it spawned and provide an action to `Terminate Running NPM Script`, the action kills the spawned process. PRs are welcome 😄
