### ISSUE TITLE
Add !terminalFocus to keyboard extensions that use Ctrl + R as the beginning of a chord

### ISSUE THREAD

**Issue by tristan957** [microsoft/vscode-npm-scripts#129]
Because of the NPM extension, Control + R recursive search is broken on Linux. Is there a way that this extension could either change its default keybindings or add `!terminalFocus` to its keybindings?

https://github.com/microsoft/vscode/issues/103581

**Comment by tristan957** [comment]
You can disable the NPM extension and suddenly recursive search starts working again.

**Comment by Tyriar** [comment]
It will also break on Windows. This would have been a problem ever since proper chord support was added to the terminal via `terminal.integrated.allowChords` (default=true).

**Comment by tristan957** [comment]
@Tyriar do you have a link to some docs I could read about extensions contributing keybindings? I'll just submit a PR myself with the !terminalFocus added.

**Comment by Tyriar** [comment]
@tristan957 here's the doc, looks like it's the same format in package.json as regular keybindings for `when`:

https://code.visualstudio.com/api/references/contribution-points#contributes.keybindings

**Comment by tristan957** [comment]
Coolio. Thank you!

**Comment by tristan957** [comment]
Of course VSC has autocomplete for `when` in the package.json 🤦
