### ISSUE TITLE
Wrong version number being reported

### ISSUE THREAD

**Issue by sfabriece** [microsoft/vscode-npm-scripts#140]
When I run npm outdated I get a different output for `latest` as the one shown when I hover over a package in package.json.

I can confirm that I only have package-lock.json in my project.

![image](https://user-images.githubusercontent.com/3108592/95980255-2dca3880-0e1d-11eb-9035-9a8c65844b89.png)

**Comment by proxxz** [comment]
I am unable to reproduce. Could you provide an example of a package this is happening for?

**Comment by sfabriece** [comment]
This turned out to be an issue with the built-in npm extension.
