### ISSUE TITLE
Exclude folders? All scripts within node_modules-whatever get validated and show up in the sidebar

### ISSUE THREAD

**Issue by BananaAcid** [microsoft/vscode-npm-scripts#145]
ALL modules in `node_modules-w32` and `node_modules-osx` get validated (errors show up) and the `node_modules-???/package.json` files clutter the npm scripts sidebar.

It would be great, to have an option to exclude specific folders.

Also: there seems to be no option to restrict finding `package.json` files to the root directory.

**Comment by ensemblebd** [comment]
It's pretty savage on a large project. The list is miles long. Very frustrating. 
Surprised there isn't a filter in Preferences.

**Comment by BananaAcid** [comment]
Package.js:Workspaces may touch this subject as well (as for yarn and npm): https://docs.npmjs.com/cli/v7/using-npm/workspaces

**Comment by egamma** [comment]
Installed modules validation has been removed, pls see #172
