### ISSUE TITLE
[Feature Request] Support PNPM workspace protocol

### ISSUE THREAD

**Issue by Faithfinder** [microsoft/vscode-npm-scripts#159]
All in the topic, basically:
https://pnpm.io/workspaces#workspace-protocol-workspace

![image](https://user-images.githubusercontent.com/25051063/129212649-77e999c7-0fa6-4cdc-86cd-a067c22b31bd.png)

**Comment by laozhu** [comment]
I need this feature too.

**Comment by egamma** [comment]
Support for installed modules has been removed pls see #172.
