### ISSUE TITLE
Feature: Run in integrated terminal

### ISSUE THREAD

**Issue by jamietre** [Microsoft/vscode-npm-scripts#16]
The integrated terminal (in insider build) is already much better than the output window because it supports ANSi colors. It would be great if this could start tasks in the integrated terminal, instead of starting a new console or using the output window.

**Comment by egamma** [comment]
Fully agreed. There is currently no API exposed to open a terminal from an extension.

**Comment by egamma** [comment]
There will be API in the August update to launch a program in the integrated terminal.

**Comment by egamma** [comment]
Closing. The extension i snow using the API for the integrated terminal.
