### ISSUE TITLE
Supress inline buttons in package.json

### ISSUE THREAD

**Issue by bernardoadc** [microsoft/vscode-npm-scripts#165]
I would like to see available scripts only in explorer/sidebar, but not inline when editing `package.json`

**Comment by egamma** [comment]
Are you referring to the 'Debug' lense shown in the screen shot below?
![image](https://user-images.githubusercontent.com/172399/176182452-e118e9fc-93c1-4a14-9889-67417d460e6a.png)

This lense is added by the JS Debugger.

//CC @connor4312

**Comment by connor4312** [comment]
This is configurable with the `debug.javascript.codelens.npmScripts` setting.
