### ISSUE TITLE
Unable to see all defined scripts.

### ISSUE THREAD

**Issue by jorawarsingh** [Microsoft/vscode-npm-scripts#17]
I have following scripts defined in my package.json

```
"scripts": {
    "validate": "npm-run-all --parallel validate-webpack:* lint",
    "validate-webpack:dev": "webpack-validator webpack.config.js --env.dev",
    "validate-webpack:prod": "webpack-validator webpack.config.js --env.prod",
    "start": "webpack-dev-server --history-api-fallback --env.dev",
    "build": "webpack -w --env.dev",
    "test": "karma start",
    "clean-dist": "rimraf dist",
    "copy-files": "cpy \"**/index.html\" favicon.ico \"../dist\" --cwd=src --parents",
    "clean-and-copy": "npm run clean-dist && npm run copy-files",
    "prebuild": "npm run clean-and-copy",
    "prebuild:prod": "npm run clean-and-copy",
    "build:prod": "webpack --env.prod",
    "lint": "tslint -c tslint.json src/**/*.ts"
  }

```
but i see only build, install , test when i do ctrl + p and type npm.

any guess why it's behaving like this or it suppose to behave like this? 

i'm usinng ubuntu 14.04

**Comment by egamma** [comment]
Only `build` and `install` are shown in the command palette directly. To get access to all commands use the 'npm: Run Script' this will show you all the scripts in the quick box, e.g.,

![image](https://cloud.githubusercontent.com/assets/172399/16834788/c6d4604a-49b5-11e6-9e5c-3e820133f9a6.png)

This works as expected.
