### ISSUE TITLE
when enable npm extension, will cause terminal's cmd+k shortkey not work.

### ISSUE THREAD

**Issue by windsonR** [microsoft/vscode-npm-scripts#174]
Issue Type: <b>Bug</b>

1. install npm extension(0.3.26)
2. open terminal.
3. use cmd+k to clear terminal. will not work.

Extension version: 0.3.26
VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:52:13.188Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

**Comment by egamma** [comment]
@windsonR 
Version 0.3.26 has added some chording keybindings starting with CMD+K. However, there are other global chording key bindings so this should not be a new problem:
![image](https://user-images.githubusercontent.com/172399/176364830-072ba3fc-032a-4ed6-aeba-e7350d57c116.png)

For me cmd+k to clear the terminal does not work even when I have all extensions disabled. 
Can you please confirm whether this has ever worked for you.

Also cmd+k to clear the terminal is only active when the terminal has focus, can you confirm that you have the terminal in focus when you press cmd+k?
![image](https://user-images.githubusercontent.com/172399/176365025-20a2934e-b9ed-417d-8dfc-893d3a18a7ad.png)

**Comment by windsonR** [comment]
for me , it(CMD+K) only bind to `Terminal: Clear`
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/11462711/176383315-7b623e83-6679-46ab-9ce0-38c76f1789bb.png">

**Comment by Tyriar** [comment]
Yes, `!terminalFocus` should be used here. It works with the other keybindings because of the `weight` property here:

https://github.com/microsoft/vscode/blob/f6786c8f2ccf01a8aae2bbc0a3ef114b44a4a845/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L1992-L1994

Extensions always override built-in keybindings though so they need more specific when clauses.

**Comment by egamma** [comment]
Fixed in 0.3.27
