### ISSUE TITLE
Option to silence npm run

### ISSUE THREAD

**Issue by texastoland** [Microsoft/vscode-npm-scripts#19]

**Comment by egamma** [comment]
@texastoland 

How about an option to not show/reveal the `npm` output channel by default. I think you always want to see error output.

**Comment by texastoland** [comment]
No I always want to see the output. I have literally never wanted to see the Node error. What's the use case for that? Generally a npm script is running an executable. I use `launch.json` for my own code.

**Comment by texastoland** [comment]
BTW #15 is loosely related and the way other extensions work.

**Comment by egamma** [comment]
I'm sorry, but now you have lost me. The title says 'option to silence npm run' and in the above comment you write 'no I always want to see output'.

Can you please elaborate what you mean by 'option to silence npm run'. What should be the effect of the proposed option.

**Comment by texastoland** [comment]
My apology I meant `npm run --silent` and suggested an option in case there's some reason it wouldn't always be desirable.

**Comment by egamma** [comment]
published the latest version to the market place.

**Comment by texastoland** [comment]
Thanks so much @egamma 🙌 I dig `tasks.json` but this plugin is much nicer for jumping into other people's projects!
