### ISSUE TITLE
Scripts with a space in name are not executed

### ISSUE THREAD

**Issue by Oneiros90** [Microsoft/vscode-npm-scripts#23]
I have some scripts in my package.json with a space in the name. I don't want to use "-" or "_" between words because i have a user-friendly GUI that reads these strings.
Can you add support for this?
Example:
```
"scripts": {
    "Install on server": "rm -r node_modules & npm install"
}
```
Error: `npm ERR! missing script: Install  `

**Comment by egamma** [comment]
Fixed through 9b5f2feb7ad7e2ed73b8cc617b64c7534baa60ee

**Comment by Oneiros90** [comment]
Awesome, thanks. Will I find the update on the vscode integrated marketplace too?

**Comment by egamma** [comment]
Not published yet, will do so soon. I'll mention it in this issue.

**Comment by egamma** [comment]
@Oneiros90 just published, sorry for the delay.

**Comment by Oneiros90** [comment]
Awesome, thank you. It works perfectly
