### ISSUE TITLE
Module 'xxx' is extraneous

### ISSUE THREAD

**Issue by web2style** [Microsoft/vscode-npm-scripts#25]
What does it mean? Can someone explain please?

**Comment by egamma** [comment]
This means you have a package installed inside your node_modules folder that isn't defined inside the package.json. This can happen when it was installed without the `--save` or `--savedev` options.

Why is this bad, the folder is shared through an SCM system and the node_modules are not checked in, then your team mate cannot just run `npm install` to have the same modules installed as you have.

**Comment by dimitarnestorov** [comment]
It can also be caused when using yarn workspaces. Can we silence this warning if the `workspaces` key is present
![image](https://user-images.githubusercontent.com/8790386/50484183-e54b4c00-09f7-11e9-9d49-8f78944c4f57.png)

**Comment by egamma** [comment]
> Can we silence this warning if the workspaces key is present

@dimitarnestorov this makes sense to me. Do you have the cycles for a PR?

**Comment by dimitarnestorov** [comment]
Sure

**Comment by JudyLipinski** [comment]
Also when switching branches.

**Comment by tjx666** [comment]
still exits in latest version. In fact `pnpm` doesn't use workspace filed in package.json, so there should no warnings when `pnpm-workspace.yaml` exits.

![image](https://user-images.githubusercontent.com/41773861/123734874-bcf67e00-d8d0-11eb-8c5d-f054c5e721f0.png)

**Comment by tjx666** [comment]
@egamma

**Comment by egamma** [comment]
For now I suggest to disable module validation in the setups described above by setting `npm.validate.enable` to `false`.

**Comment by softboy99** [comment]
still exits in latest version. In fact pnpm doesn't use workspace filed in package.json, so there should no warnings when pnpm-workspace.yaml exits.

**Comment by dvakatsiienko** [comment]
@softboy99 having this issue too

**Comment by hyoretsu** [comment]
Still having this out of nowhere

**Comment by laozhu** [comment]
The same issue with pnpm.

**Comment by GiancarlosIO** [comment]
+1 to silence when a `pnpm-workspace.yaml` exists

**Comment by wottpal** [comment]
> +1 to silence when a `pnpm-workspace.yaml` exists

Is there any issue/ticket tracking this? All these errors really get annoying when using pnpm within a monorepo for me.

**Comment by GiancarlosIO** [comment]
> @GiancarlosIO Is there any issue/ticket tracking this? All these errors really get annoying when using pnpm within a monorepo for me.

@wottpal as far as I know there is no issue/ticket for tracking this specific problem :(
