### ISSUE TITLE
Contribute npm run scripts to `Run Task`

### ISSUE THREAD

**Issue by Eoksni** [microsoft/vscode-npm-scripts#35]
Release notes for [recent vscode update](https://code.visualstudio.com/updates/v1_11) say:

> We also now allow extensions to contribute tasks to the Run Task Quick Pick list programmatically. This opens VS Code up for use cases where an extension wants to add support for a specific build system and wants to contribute corresponding tasks. An example is the npm extension that can now contribute scripts defined in the package.json as tasks to VS Code programmatically.

Would love to see it being actually implemented!

**Comment by egamma** [comment]
@Eoksni Agreed. Actually we use the npm scripts as a test case for the new API. Making the change available in the extension requires that API graduates out of the 'provisional' state ( we do not allow to publish extensions that use API in the provisional state).

**Comment by skeet70** [comment]
@egamma where is the code using that new API? Been cruising around these various repos and this is the closest I've come. I'd love to publish an extension to add pre-configured task runner configs for [`pulp`](https://github.com/bodil/pulp). I can't seem to find documentation of the new API feature, or code using it.

**Comment by egamma** [comment]
@skeet70 here is the code https://github.com/Microsoft/vscode/blob/master/extensions/npm/src/main.ts.

However, we have decided to keep the Task provider API proposed for another iteration. This means we still can change it and you cannot publish an extension using proposed API to the market place.

**Comment by egamma** [comment]
Closing the the Task provider API is now available.
