### ISSUE TITLE
Support for running more than 1 NPM script

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode-npm-scripts#37]
Hello,

please add support to run multiple npm scripts, because right now I can run only 1 script.

**Comment by langdonx** [comment]
Has this always been the case?  I thought I was able to run my `npm run lint` command after running `npm start`, which ends up running infinitely because of a watch.

**Comment by fokusferit** [comment]
Normally, if you would need to run multiple npm commands ,e.g. lint->test->build etc.. you can easily wrap them into one npm command and run it, maybe that is solving the case here ?

**Comment by maarek** [comment]
I came across this as I need to run both an app server and bucklescript watcher to compile code. I'm not sure of the best way to go about this but it would be great just to be able to run two separate npm commands in separate terminals.

**Comment by egamma** [comment]
There is now support for running npm scripts in an npm extension bundled with VS Code. You can run an npm script using `Tasks>Run Script...` provided in the menu bar. @maarek please let me know whether this covers your needs.

**Comment by maarek** [comment]
@egamma You mean Tasks> Run Task? I can continue to look into that as an option but I was running into issues with it as I am using cygwin zsh shell on windows and it kept trying to pass a /d argument to it that would fail to start the terminal. This is probably not the forum to troubleshoot that issue but here is my integrated terminal settings: 

    "terminal.integrated.shell.windows": "C:\\.babun\\cygwin\\bin\\zsh.exe",
    "terminal.integrated.shellArgs.windows": [],

**Comment by egamma** [comment]
@maarek yes I meant ´Tasks>Run Task` sorry.

Can you please file an issue against the vscode repository with regard to the cygwin zsh, then we can track it over there.
