### ISSUE TITLE
After closing npm in terminal I can't run command anymore

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode-npm-scripts#38]
Hello,

I run NPM script with this extension and then I close npm terminal which is integrated after running script and I can't launch anymore NPM script with this extension, need to do Reload Window or close VS Code.

To reproduce simple run NPM command which will be alive forever. Close it in your terminal by `Kill Terminal` and try to run NPM command with this extension, you can't.

**Comment by egamma** [comment]
published in 0.2.0.
