### ISSUE TITLE
So many `npm-debug.log.xxxxx` are generated after package.json save.

### ISSUE THREAD

**Issue by meowtec** [microsoft/vscode-npm-scripts#41]
<img width="358" alt="2017-07-18 11 37 43" src="https://user-images.githubusercontent.com/4006436/28299750-a010e530-6bad-11e7-92bb-2be1f67060e1.png">

**Comment by egamma** [comment]
@meowtec can you please attach one of the npm-debug.logs to this issue.

**Comment by meowtec** [comment]
@egamma just empty file.

I can not reproduce it now. I don't know why.
