### ISSUE TITLE
Split dependencies validation into an other extension

### ISSUE THREAD

**Issue by dinoboff** [microsoft/vscode-npm-scripts#43]
AFAIK, vsc autodetect npm scripts ("Tasks: run task" > *select npm script*). I would like to disable this extension (especially since it's duplication `npm.runSilent` setting) but I would like to keep using dependencies validation. Would it be possible to split the features into two extensions?

**Comment by egamma** [comment]
@dinoboff I'll fix the duplicate setting soon. Once this setting is fixed I don't think that the bundled npm support and the npm support in this extension bite each other (I'm the author of both) and you can use them side by side without problems.

**Comment by egamma** [comment]
>My intent is to remove the script running support in this extension in favor of the one provided for task running as soon as the bundled one has a similar set of features.

This is now the case - closing.
