### ISSUE TITLE
when I intsall node js i am facing issue 

### ISSUE THREAD

**Issue by VenkatJandhyam** [Microsoft/vscode-npm-scripts#47]
Hello here is the link I am following 

https://dzone.com/articles/angular-2-and-spring-boot-development-environment

when I check with cmd prompt npm -v i am getting the below error.

'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.
5.5.1

How to get rid of this error.

I am able to see the nodejs in system variables.

Becuase of that I am not able to install angular cli

**Comment by egamma** [comment]
@VenkatJandhyam this issue has nothing to do with VS Code (and VS Code isn't even mentioned in the article). I don't know the answer, suggest to ask your question some where else.
