### ISSUE TITLE
'npm install -g jslint

### ISSUE THREAD

**Issue by hawkmaster** [Microsoft/vscode-npm-scripts#48]
Hello,
I have installed the npm package in Visual Studio Code. I need to run
'npm install -g jslint' because of errors.
But how can I run this command within Visual Studio Code?
thanks
regards
hawk

**Comment by egamma** [comment]
The recommended way is to run the command in the integrated terminal.

**Comment by hawkmaster** [comment]
sorry, but what di you mean with "integrated terminal."?
Do you mean within Visual Studio Code? How to open the integrated terminal?

**Comment by egamma** [comment]
>Do you mean within Visual Studio Code? How to open the integrated terminal?

yes, pls try the menu item `View>IntegratedTerminal`
