### ISSUE TITLE
Usage with monorepos / lerna - support glob patterns for `npm.includeDirectories`

### ISSUE THREAD

**Issue by chrisblossom** [microsoft/vscode-npm-scripts#49]
Is there a guide to get this plugin to work with monorepos such as lerna? Is it possible?

Thank you!

**Comment by egamma** [comment]
There is the setting `npm.includeDirectories` that you could define for the packages in a monorepo, e.g,
```json
"npm.includeDirectories": [
		"packages/package1",
		"packages/package2"
	]
```

The scripts will then be collected from all packages, but they will be run using npm and not lerna.

**Comment by chrisblossom** [comment]
I should have included in my original post the first thing I tried was:
```js
"npm.includeDirectories": ["packages/*/"]
```

I guess all packages would need to be added individually?

**Comment by egamma** [comment]
yes, you have to add all package directories individually.   Support for glob patterns would be a valid feature request

**Comment by egamma** [comment]
Closing since the extension has been deprecated, pls see https://github.com/microsoft/vscode-npm-scripts#node-npm
