### ISSUE TITLE
Question: Debugging and npm scripts

### ISSUE THREAD

**Issue by blesh** [Microsoft/vscode-npm-scripts#5]
I'm looking for a way to run some npm scripts in Visual Studio Code (to lint/build/etc), then run, say, `jasmine` in debug mode from VSCode.

Currently to debug my tests, I have to:

```
npm run build_stuff
jasmine
```

I'd like to run the npm run build_stuff out of debug mode, then debug `jasmine`, which is running specs in my project.

Is it the intent of this extension to help support that use case?

**Comment by blesh** [comment]
FWIW: The project I'm using this on is here: http://github.com/ReactiveX/RxJS

**Comment by egamma** [comment]
For this scenario I would recommend to look into the `task` support from Code. Please see: https://code.visualstudio.com/docs/editor/tasks.

**Comment by blesh** [comment]
Thanks that was interesting and helpful.

**Comment by sparty02** [comment]
@blesh did you end up with a useful recipe for this?  Ideally, I'd like to just start an npm run script in "debug mode"

**Comment by blesh** [comment]
@sparty02 unfortunately not. I'm still basically just using VSCode as a text editor because I haven't been able to use debug mode with my build process. So I use node-inspector for now.

**Comment by egamma** [comment]
How about you leave your build process as is, but once a test fails then you run tests under the debugger. To do so you can define a launch configuration as follows:

- Press F5 or the debug icon
- select `node` from the quick box
- edit the launch.json as follows (this assumes that jasmine is installed locally).

```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "jasmine",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/node_modules/jasmine/bin/jasmine.js",
			"stopOnEntry": false,
			"args": [],
			"cwd": "${workspaceRoot}",
			"runtimeArgs": [
				"--nolazy"
			],
			"env": {
				"NODE_ENV": "development"
			}
		}
	]
}
```
If you always want to run the tests under the debugger then you could do what is described in this blog for [debugging mocha tests](http://scottaddie.com/2015/10/22/debugging-mocha-unit-tests-in-visual-studio-code/), that is, you launch the tests and attach the debugger.

**Comment by blesh** [comment]
@egamma ... thanks, I'll give that a try next time I need to step into the code!

**Comment by fabian-dev** [comment]
The configuration Erich suggested works fine for me. Thanks!

I do as well debug other gulp tasks this way by adding new launch.js configurations this way:
`"program": "${workspaceRoot}/node_modules/gulp/bin/gulp.js"`
`"args": [ "jasmine" ]`
