### ISSUE TITLE
npm Terminate, never kills the process

### ISSUE THREAD

**Issue by ayyash** [microsoft/vscode-npm-scripts#50]
When I run > npm from vscode as a task, then use > npm: Terminate, the output message:
**Killing process npm start (pid: xxxx)**

And it's stuck forever, the task is never killed, until I restart vscode. This has been happening for a very long time (over a year). My current vscode version:

Version 1.20.0-insider
Commit b36655544f413f67aec02d64ce619d165749b957
Date 2018-01-15T05:14:00.163Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

![image](https://user-images.githubusercontent.com/1110344/34930484-4075220e-f9d2-11e7-993f-13a2bef27d18.png)

**Comment by egamma** [comment]
@ayyash this statement is not clear to me:

> When I run > npm from vscode as a task

How do you exactly start the npm script using ´Tasks>Run Tasks´ or  ´npm: start´, ´npm: Run Script´ ?

**Comment by ayyash** [comment]
using > npm: Run Script

**Comment by dmaglio** [comment]
same issue for me with vsocde 1.21.1 and fedora 27 or windows 7

**Comment by kovyazin** [comment]
I have too this problem, run script using "Run script"

**Comment by egamma** [comment]
The npm script running support has been replaced in favor of the npm script running provided by the VS Code core out of the box, pls see https://code.visualstudio.com/docs/editor/tasks#_task-autodetection
