### ISSUE TITLE
package.json validation (missing modules) not working for the devDependencies

### ISSUE THREAD

**Issue by Phoenix359** [microsoft/vscode-npm-scripts#53]
**Behaviour:**
When I add a new dependency to the 'dependencies' node in the package.json I get the 'not installed' warning. [correct]
When I add that same dependency to the 'devDependencies' node I do not get the warning. [not correct]
When I add the dependency to both the 'dependencies' & 'devDependencies' node. I get a warning but only for the one in the 'devDependencies' node. [semi correct]

**Expected behaviour:**
I always get a warning when I add a new dependency to the package.json.
If I add a dependency to both nodes I expect 2 warnings.

![dependencies](https://user-images.githubusercontent.com/7901130/35911461-28eaecba-0bfa-11e8-932e-be432893bbf7.jpg)
![devdependencies](https://user-images.githubusercontent.com/7901130/35911465-2a8ba924-0bfa-11e8-9ce6-85342c45c869.jpg)
![both](https://user-images.githubusercontent.com/7901130/35911470-2be33198-0bfa-11e8-828e-6477928681eb.jpg)

**Comment by ugrupp** [comment]
+1

**Comment by Phoenix359** [comment]
bump

**Comment by egamma** [comment]
The validation is currently done by shelling out to npm using `npm list --depth`.
It looks like npm now also supports `npm list -depth 0 -dev true` for development dependencies. So this should be straightfoward to implement. PRs welcome.

**Comment by jarod-legault** [comment]
I ran `npm ls --depth 0`, and it showed both dependencies and devDependencies, so I don't think adding `-dev true` will help. I think that would just show **only** devDependencies and exclude dependencies.

**Comment by egamma** [comment]
module dependency validation support has been removed, pls see https://github.com/microsoft/vscode-npm-scripts/issues/172
