### ISSUE TITLE
Support globs for includeDirectories setting

### ISSUE THREAD

**Issue by alasdairhurst** [microsoft/vscode-npm-scripts#55]
In my use-case, my repo is lerna monorepo, where all my NPM packages are under the /packages folder, and each have their own package.json. The root also has a package.json

I can currently define "npm.includeDirectories" with an exhaustive list of all packages, but it gets painful to maintain, especially with 20+ packages:
```
	"npm.includeDirectories": [
		"packages/module1",
		"packages/module2",
		"packages/module3",
		"packages/module4",
		"packages/module5",
		"packages/module6",
		"packages/module7",
		"packages/module8",
               ...etc
	],
```

What I would like to do, is use a glob to match all packages inside the packages folder, which will include any new packages automatically:
```
"npm.includeDirectories": [
    "packages/*"
],
```

**Comment by egamma** [comment]
@alasdairhurst The built-in npm task provider is now support to search for scripts in subdirectories and it also provides an exclude option, pls see https://github.com/Microsoft/vscode/tree/master/extensions/npm. Does this cover your needs?

**Comment by alasdairhurst** [comment]
@egamma, yup, this works for me. Thanks
