### ISSUE TITLE
Feature request - MRU npm scripts

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode-npm-scripts#56]
Feature request

When using the command palette to run npm scripts, they are alphabetized. OFten we run the same 1 or 2 repeatedly. It would be nice if the most frequently run script appeared first (once VS Code has seen them a few times). Kind of like how the most recently used files show up

**Comment by egamma** [comment]
@johnpapa have you tried the new Task based support to run scripts `Tasks>Run Task...`, this command creates a Task for the detected npm scripts. This command will provide a list of recently used tasks, see below. 

![image](https://user-images.githubusercontent.com/172399/37879838-1537a3b2-307f-11e8-8dd1-2ddd01c92049.png)

**Comment by egamma** [comment]
The user can either select Run Tasks... from the menu
![image](https://user-images.githubusercontent.com/172399/38331431-8a55a38e-3853-11e8-9d31-ac1eaec5dcc2.png)

Or the user can type CTRL+P and then enter ´task prefix´
