### ISSUE TITLE
Question: npm scripts in project subdirectory?

### ISSUE THREAD

**Issue by bernardop** [Microsoft/vscode-npm-scripts#6]
Can I specify which package.json file to use? I have an app within my app that has its own package.json file with its own npm scripts. Is there a way that could run those instead of the main ones?

**Comment by egamma** [comment]
Currently this is not supported, but this should be straightforward to add, do you want to give it a try ?

**Comment by bernardop** [comment]
Sure, I'll give it a shot this week.

**Comment by djanosik** [comment]
Looks pretty good. Can you update the extension?

**Comment by egamma** [comment]
Published the extension with the PR.
