### ISSUE TITLE
npm script response time

### ISSUE THREAD

**Issue by VenkattaPidikiti** [Microsoft/vscode-npm-scripts#63]
- Extension Name: vscode-npm-script
- Extension Version: 0.3.5
- OS Version: Windows_NT x64 10.0.14393
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 1681,
		"activateCallTime": 44,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:json"
	}
}
```

**Comment by egamma** [comment]
closing pls see Microsoft/vscode#60318
