### ISSUE TITLE
Parallel Scripts when running multiple scripts

### ISSUE THREAD

**Issue by joezimjs** [Microsoft/vscode-npm-scripts#68]
I have a workspace that contains 3 interdependent projects that all need to be `npm start`ed. If I use this extension to start them (via `npm:Start` -> `All`... or even individually instead of "all") they all attempt to run in the same terminal sequentially (I have "Run In Terminal" option selected). The problem is that they are all long-running server tasks, so it'll only actually run the first one. I need a way to have these all run in separate terminal processes at the same time.  I'd also prefer if they were done using the "Split Terminal" function so I can watch all 3 at once, but if they all launch in their own terminal tab, that's fine too. I don't know if you want to make this a configuration setting or just one of the options to pop up in the command palette as you try to run it.

**Comment by egamma** [comment]
Support for running npm scripts as tasks is now provided by the bundled npm extension. This extension detects npm scripts as tasks https://code.visualstudio.com/Docs/editor/tasks#_task-autodetection. I have currently no plans to add functionality to this extension.

Please try the support provided by this extension. It supports running multiple tasks at the same time. If the support is not sufficient then pls file feature requests against vscode.
