### ISSUE TITLE
Feature Request - Add when clause contexts to keybindings

### ISSUE THREAD

**Issue by patrickgreenwell** [Microsoft/vscode-npm-scripts#70]
Please add [when clause contexts](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts) to the keybindings included so that the open recent default can be used. 

Please work with the vscode team to come to some resolution, I've also opened an issue there [#67758](https://github.com/Microsoft/vscode/issues/67758).

Either put some sort of context on the keybindings, with language specifics or something so that single chord keybindings aren't ignored/hidden.

**Comment by egamma** [comment]
@patrickgreenwell I appreciate your passion for this issue. Our recommendation is to customize the keybindings to the way it works best for you. 

When clause contexts do not really help in this case since these commands should be available in any context.

**Comment by patrickgreenwell** [comment]
@egamma I'd argue that context does matter.

Do I actually want to run an npm script on a new workbench window that doesn't have a file or folder or workspace open? 

I get that this issue isn't the highest priority, It just really irksome when you quickly trying to open back up a recent project/repo/workspace and realize the keybinding for open recent isn't working, when it's supposed to come standard out of the box. 

I'll ask even though it's not a high priority on the list, that it should be something to work towards. Even if it's a thing you push onto the vscode editor team to not auto-timeout key-chords if a second stroke isn't placed, or offer an option to execute single stroke ones if hidden by two stroke.  I'll either remove the keybindings from this extension or uninstall for the time being.

I do have one final suggestion:
 Move the Comment about the Keybinding breaking from the bottom of the Readme.md to the top so it is visible in the VSCode marketplace view inside code

Thanks for the work you do btw on maintaining and supporting these extensions and vscode. I wouldn't be able to do my day job without all the work you and others have put in to make such and awesome code editor!

**Comment by mchelen** [comment]
For what it's worth, I also find this default extremely bothersome, and I often remove the extension. I added some suggestions to #71 to make it easier for users to disable this.
