### ISSUE TITLE
Update list

### ISSUE THREAD

**Issue by WORMSS** [Microsoft/vscode-npm-scripts#74]
When new scripts are added to package.json, there is no way to update the list of scripts in the panel without restarting vscode. 

Needs like a refresh icon like the explorer panel.

![image](https://user-images.githubusercontent.com/1384537/56025210-922ca900-5d09-11e9-8df0-2ad24043dca4.png)

**Comment by egamma** [comment]
@WORMSS not sure which extension you are using, but the npm script extension bundled with VS Code has a refresh button.

<img width="176" alt="image" src="https://user-images.githubusercontent.com/172399/56027618-acb94f00-5d16-11e9-9d42-9c2ec7d50e97.png">

**Comment by WORMSS** [comment]
@egamma You are indeed correct, I seem to have an extension installed.

How do you get to the npm script extension bundled with VS Code?

**Comment by egamma** [comment]
@WORMSS you already have it, just enable it using the setting `npm.enableScriptExplorer`.

**Comment by WORMSS** [comment]
Yes, I understood I had it already. That is what built-in means obviously. 

This was why I was asking **how to get to it**. As I was looking around `Open view` and and right clicking everywhere to see where the hell it had been hidden. I seen that the built in extension was enabled from `@builtin npm` but it was just nowhere to be seen.

**Comment by egamma** [comment]
@WORMSS agreed the discoverability isn't great. I didn't want to show it by default to not pollute the Explorer. However, since you mention you looked in 'Open View..." I'll look into supporting that the npm script explorer is visible in Open View but not visible in the Explorer by default.

**Comment by WORMSS** [comment]
Thank you. 👍 

I just noticed (I opened up a different project). And it shows submodules too (which the other extension didn't do).. Very nice.
