### ISSUE TITLE
Touchbar commands changes path to home directory when setting `npm.bin`

### ISSUE THREAD

**Issue by paulbatessonos** [microsoft/vscode-npm-scripts#78]
Using the command palette in VS code correctly uses `yarn` for the command executed. With the recent release of this extension (addition of Touchbar controls) the touchbar was using `npm` instead or `yarn` as defined in my user `settings.json` (`npm.packageManager`).

I set `npm.bin` to point to yarn, but this has a undesired consequence of always first executing `cd ${HOME}` and then running the command (`yarn install` in this case).

**To Reproduce**
Add the following to your `settings.json`:

```
"npm.bin": "yarn",
"npm.packageManager": "yarn"
"npm.runInTerminal": true,
```

1. Open a Node.js project on macOS
2. Using the Touchbar, tap Install.

**Comment by matextrem** [comment]
I can't reproduce the error. I have installed yarn and the scripts works with the VS code pallete and touchbar controls as well.

**Comment by paulbatessonos** [comment]
Thanks @matextrem. I'll debug my bash profile configuration incase there is something causing this. I'll get back to you.

**Comment by paulbatessonos** [comment]
I completely disabled any profile configuration, relaunched VS Code, checked other login profiles.

This is the VS code terminal output when using the Touchbar...

`cd "/Users/test.user"` is still getting injected into the execution, only when executing from the touchbar.

```
user:test-project-node test.user $ cd "/Users/test.user"
user:~ test.user $ /usr/local/bin/yarn install
yarn install v1.15.2
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
```

**Comment by paulbatessonos** [comment]
Just tried it on another developer's machine, free extension install, different project - same result. It really does not matter if using yarn or not. All I set was the new `npm.enableTouchbar: true` on his configuration.

Using touchbar - changes to user directory
Using command palette - changes to project directory

**Comment by matextrem** [comment]
@paulbatessonos It's really weird. I think you may have any misconfiguration in your project. I'm trying to follow the steps as you did but i could make it work. Touchbar controls are only shortcuts to the npm task. They are running the same script as if you use it from the VS Code command palette.

**Comment by srinathwarrier** [comment]
@matextrem , I am facing the exact same issue as @paulbatessonos . Any further update here?
