### ISSUE TITLE
Use `yarn` if a `yarn.lock` is detected

### ISSUE THREAD

**Issue by arcanis** [microsoft/vscode-npm-scripts#81]
In Yarn 2 (or PnP installs in general), it will become impossible for npm to run the scripts if the dependencies have been installed by Yarn. This will become more significant now that this extension is enabled by default.

You should detect whether Yarn is used (by checking whether the project uses a `yarn.lock` file) and use `yarn run` if needed instead of `npm run-script`.

As a side note, it would be appreciable if the [command titles](https://github.com/microsoft/vscode-npm-scripts/blob/0814599bc0edabe0e2a66de579f2f9cb9924be90/src/main.ts#L88) were switched to their `yarn` counterpart in such instances, as it would otherwise be confusing to users.

**Comment by GasimGasimzada** [comment]
+1 for the command titles. Until I opened issues in this repo, I had no idea whether I was running yarn or npm.

**Comment by lahvey** [comment]
It's better if it can be configured to use `yarn` or `npm`. I have to delete `yarn.lock` if I don't want to use yarn for some reason.

**Comment by egamma** [comment]
The npm script running support that is provided by VS Code is now using yarn if a yarn.lock is detected. The script running provided by this extension is now deprecated. Pls see https://code.visualstudio.com/Docs/editor/tasks#_task-autodetection
