### ISSUE TITLE
Beta versions of a package erroneously show as a downgrade

### ISSUE THREAD

**Issue by SConaway** [microsoft/vscode-npm-scripts#83]
Beta versions of a package erroneously show as a downgrade. See attached screenshots. I've noticed the problem with several packages.

Downgrade: 
![Screen Shot 2020-02-18 at 4 11 49 PM](https://user-images.githubusercontent.com/20807660/75085442-32cd2700-54de-11ea-9753-66c7441dc888.png)

Correct icon: 
![Screen Shot 2020-02-18 at 4 12 00 PM](https://user-images.githubusercontent.com/20807660/75085444-3cef2580-54de-11ea-8bc9-557ca2920591.png)

**Comment by egamma** [comment]
Node module validation has been deprecated pls see https://github.com/microsoft/vscode-npm-scripts/issues/172
